export const SET_STOCK_DATA = 'SET_STOCK_DATA';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';

// export const SET_PREV_PRICE = 'SET_PREV_PRICE';

export const SET_WATCHING_GROUP = 'SET_WATCHING_GROUP';

export const SET_DELETE_WATCHING_GROUP = 'SET_DELETE_WATCHING_GROUP';
